// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vygcsptjdylwdsvsiyod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5Z2NzcHRqZHlsd2RzdnNpeW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDAxMTUsImV4cCI6MjA2ODQxNjExNX0.teyfzCYHAsYgcMTb3t8E1HuYn19Vc2dyeZlgrhMZqMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});